# Generated by Django 5.2.5 on 2025-12-28 02:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthNonce',
            fields=[
                ('wallet_address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('nonce', models.CharField(help_text='Chaîne aléatoire à signer', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('current_menu', models.CharField(default='HOME', max_length=50)),
                ('input_buffer', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session USSD',
                'indexes': [models.Index(fields=['phone_number'], name='identity_us_phone_n_4bd585_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(help_text='Adresse publique Ethereum/Polygon (0x...)', max_length=42, unique=True)),
                ('phone_hash', models.CharField(blank=True, help_text='SHA-256 du numéro de téléphone', max_length=64, null=True, unique=True)),
                ('encrypted_phone', models.TextField(blank=True, help_text='Numéro chiffré pour notifications', null=True)),
                ('role', models.CharField(choices=[('USER', 'Utilisateur Standard'), ('WITNESS', 'Témoin Certifié'), ('CHIEF', 'Chef de Localité'), ('ADMIN', 'Administrateur')], db_index=True, default='USER', max_length=20)),
                ('reputation_score', models.IntegerField(default=50, help_text='Score 0-100 basé sur la fiabilité')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'indexes': [models.Index(fields=['phone_hash'], name='identity_us_phone_h_f30b26_idx'), models.Index(fields=['role'], name='identity_us_role_d94918_idx')],
            },
        ),
    ]
