# Generated by Django 5.2.5 on 2025-12-28 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_phone_h_815073_idx',
            old_name='identity_us_phone_h_f30b26_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_role_0ace22_idx',
            old_name='identity_us_role_d94918_idx',
        ),
        migrations.RemoveField(
            model_name='authnonce',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='encrypted_phone',
            field=models.CharField(blank=True, help_text='Numéro chiffré pour notifications', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='authnonce',
            table='auth_nonces',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
