# Generated by Django 5.2.5 on 2025-12-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_rename_identity_us_phone_h_f30b26_idx_users_phone_h_815073_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ussdsession',
            new_name='ussd_sessio_phone_n_a4ce08_idx',
            old_name='identity_us_phone_n_4bd585_idx',
        ),
        migrations.AlterModelTable(
            name='ussdsession',
            table='ussd_sessions',
        ),
    ]
