# Generated by Django 5.2.5 on 2025-12-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_rename_identity_us_phone_n_4bd585_idx_ussd_sessio_phone_n_a4ce08_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Nom et Prénom (pas de chiffres)', max_length=255, null=True),
        ),
    ]
