# Generated by Django 5.2.5 on 2026-02-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Benin', help_text='Pays de résidence', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, help_text='Arrondissement / Commune', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.CharField(blank=True, help_text='Quartier / Village', max_length=100, null=True),
        ),
    ]
