# Generated by Django 5.2.5 on 2026-02-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_user_country_user_district_user_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Adresse publique Ethereum/Polygon (Optionnel)', max_length=42, null=True, unique=True),
        ),
    ]
