# Generated by Django 5.2.5 on 2026-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur Standard'), ('WITNESS', 'Témoin Certifié'), ('CHIEF', 'Chef de Localité'), ('ADMIN', 'Administrateur'), ('NOTARY', 'Notaire Certifié')], db_index=True, default='USER', max_length=20),
        ),
    ]
