# Generated by Django 5.2.5 on 2025-12-28 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainSyncStatus',
            fields=[
                ('contract_address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('chain_id', models.IntegerField(default=137, help_text='Chain ID (ex: 137 Polygon)')),
                ('last_processed_block', models.BigIntegerField(default=0)),
                ('sync_status', models.CharField(choices=[('OK', 'Synchronisé'), ('LAGGING', 'En retard'), ('STOPPED', 'Arrêté / Erreur')], default='OK', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_chain_id', models.DecimalField(blank=True, decimal_places=0, help_text='Token ID (uint256) sur le contrat', max_digits=78, null=True, unique=True)),
                ('gps_centroid', models.JSONField(help_text='Point central {lat: float, lng: float}')),
                ('gps_boundaries', models.JSONField(help_text='Limites exactes [ {lat, lng}, ... ]')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon / En attente'), ('VALIDATING', 'En cours de validation'), ('ON_CHAIN', 'Sécurisé sur Blockchain'), ('DISPUTED', 'En litige')], db_index=True, default='DRAFT', max_length=20)),
                ('last_sync_block', models.BigIntegerField(blank=True, help_text='Dernier bloc synchronisé', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(db_column='owner_wallet', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL, to_field='wallet_address')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipfs_cid', models.CharField(help_text='Content ID IPFS (ex: Qm...)', max_length=64)),
                ('media_type', models.CharField(choices=[('PHOTO_LAND', 'Photo du Terrain'), ('PHOTO_DOC', 'Photo Document Papier'), ('VIDEO_DRONE', 'Vidéo Drone')], max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Hash confirmé sur la blockchain ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='land_registry.property')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='land_regist_status_f2a2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner'], name='land_regist_owner_w_7cc2c7_idx'),
        ),
    ]
