# Generated by Django 5.2.5 on 2025-12-28 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='land_regist_owner_w_7cc2c7_idx',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='owner_wallet',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_status_e6008a_idx',
            old_name='land_regist_status_f2a2bc_idx',
        ),
        migrations.RemoveField(
            model_name='blockchainsyncstatus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='propertymedia',
            name='created_at',
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner_wallet'], name='properties_owner_w_036fcf_idx'),
        ),
        migrations.AlterModelTable(
            name='blockchainsyncstatus',
            table='blockchain_sync_status',
        ),
        migrations.AlterModelTable(
            name='property',
            table='properties',
        ),
        migrations.AlterModelTable(
            name='propertymedia',
            table='property_media',
        ),
    ]
