# Generated by Django 5.2.5 on 2026-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0002_remove_property_land_regist_owner_w_7cc2c7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='property_media/'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='media_type',
            field=models.CharField(choices=[('PHOTO_LAND', 'Photo du Terrain'), ('PHOTO_DOC', 'Photo Document Papier'), ('VIDEO_DRONE', 'Vidéo Drone'), ('LEGAL_DOC', 'Document Juridique (PDF/Scan)'), ('OTHER_MEDIA', 'Autre Média')], max_length=20),
        ),
    ]
