# Generated by Django 5.2.5 on 2026-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0003_propertymedia_file_alter_propertymedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_cadastral',
            field=models.CharField(blank=True, help_text='Superficie format cadastral (ex: 01ha 20a 15ca)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='area_sqm',
            field=models.FloatField(blank=True, help_text='Superficie en m²', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, help_text="Nom de l'arrondissement", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='village',
            field=models.CharField(blank=True, help_text='Quartier / Village', max_length=100, null=True),
        ),
    ]
