# Generated by Django 5.2.5 on 2026-02-04 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0004_property_area_cadastral_property_area_sqm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='surveyor_name',
            field=models.CharField(blank=True, help_text="Nom de l'ingénieur géomètre", max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PropertyWitness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('id_card_photo', models.FileField(blank=True, null=True, upload_to='witness_ids/')),
                ('ipfs_cid', models.CharField(blank=True, help_text="CID de la pièce d'identité", max_length=64, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='land_registry.property')),
            ],
            options={
                'verbose_name': 'Témoin',
                'verbose_name_plural': 'Témoins',
                'db_table': 'property_witnesses',
            },
        ),
    ]
