# Generated by Django 5.2.5 on 2026-02-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0005_property_surveyor_name_propertywitness'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='Benin', help_text='Pays de la parcelle', max_length=100),
        ),
    ]
