# Generated by Django 5.2.5 on 2026-02-09 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0006_property_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedSurveyor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(help_text="Numéro d'agrément officiel", max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Cabinet ou Administration', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Géomètre Agréé',
                'verbose_name_plural': 'Géomètres Agréés',
                'db_table': 'authorized_surveyors',
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon / En attente'), ('PENDING_SURVEYOR', 'En attente attestation géomètre'), ('VALIDATING', 'En cours de validation communautaire'), ('ON_CHAIN', 'Sécurisé sur Blockchain'), ('DISPUTED', 'En litige')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='surveyor_name',
            field=models.CharField(blank=True, help_text='Nom saisi (si hors liste)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='land_registry.authorizedsurveyor'),
        ),
    ]
