# Generated by Django 5.2.5 on 2026-02-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0007_authorizedsurveyor_alter_property_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertywitness',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='propertywitness',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Le témoin a-t-il validé son implication ?'),
        ),
    ]
