# Generated by Django 5.2.5 on 2026-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0008_propertywitness_email_propertywitness_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_surveyor_validated',
            field=models.BooleanField(default=False, help_text='Le géomètre a-t-il certifié les mesures ?'),
        ),
    ]
