# Generated by Django 5.2.5 on 2025-12-28 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(help_text='Hash de la transaction blockchain', max_length=66, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='MINT, TRANSFER, VALIDATE, DISPUTE', max_length=50)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(blank=True, max_length=42, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_fiat', models.DecimalField(decimal_places=2, help_text='Prix affiché en FCFA', max_digits=15)),
                ('price_crypto', models.DecimalField(decimal_places=6, help_text='Équivalent stablecoin (cUSD)', max_digits=18)),
                ('escrow_contract', models.CharField(blank=True, help_text='Adresse du contrat séquestre déployé', max_length=42)),
                ('status', models.CharField(choices=[('ACTIVE', 'En vente'), ('SOLD', 'Vendu'), ('CANCELLED', 'Annulé')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='land_registry.property')),
                ('seller', models.ForeignKey(db_column='seller_wallet', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='wallet_address')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_wallet', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, to_field='wallet_address')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'read_at'], name='marketplace_user_wa_a2c26f_idx')],
            },
        ),
    ]
