# Generated by Django 5.2.5 on 2025-12-28 13:46

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(help_text='Hash de la transaction blockchain', max_length=66, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='MINT, TRANSFER, VALIDATE, DISPUTE', max_length=50)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(blank=True, max_length=42, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Transactions History',
                'db_table': 'transactions_history',
            },
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='marketplace_user_wa_a2c26f_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='user_wallet',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_wallet', 'read_at'], name='notificatio_user_wa_d9f7c7_idx'),
        ),
        migrations.AlterModelTable(
            name='listing',
            table='listings',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
