# Generated by Django 5.2.5 on 2026-03-02 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplaceinquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceinquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceinquiry',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='marketplaceinquiry',
            index=models.Index(fields=['created_at'], name='marketplace_created_055fab_idx'),
        ),
    ]
