# Generated by Django 5.2.5 on 2026-03-02 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_registry', '0009_property_is_surveyor_validated'),
        ('marketplace', '0004_marketplaceinquiry_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('view_type', models.CharField(default='MARKETPLACE_HOME', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consultation Marketplace',
                'db_table': 'marketplace_views',
            },
        ),
        migrations.RemoveIndex(
            model_name='marketplaceinquiry',
            name='marketplace_created_055fab_idx',
        ),
        migrations.RemoveField(
            model_name='marketplaceinquiry',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='marketplaceinquiry',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='marketplaceview',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land_registry.property'),
        ),
        migrations.AddField(
            model_name='marketplaceview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
