# Generated by Django 5.2.5 on 2026-03-03 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land_registry', '0009_property_is_surveyor_validated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom complet du Notaire', max_length=255)),
                ('office_name', models.CharField(help_text="Nom de l'étude / cabinet", max_length=255)),
                ('license_number', models.CharField(help_text='Numéro de licence officielle', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(help_text="Adresse physique de l'étude")),
                ('city', models.CharField(default='Cotonou', max_length=100)),
                ('gps_location', models.JSONField(blank=True, help_text='Localisation {lat: float, lng: float}', null=True)),
                ('avg_processing_time_days', models.IntegerField(default=30, help_text='Temps moyen de traitement constaté')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié par iLôt')),
                ('pricing_guide', models.JSONField(blank=True, help_text='Grille tarifaire standardisée', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notaire',
                'verbose_name_plural': 'Notaires',
                'db_table': 'notaries',
            },
        ),
        migrations.CreateModel(
            name='TransactionFolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STEP1_NOTARY_SELECTED', '1. Notaire Choisi'), ('STEP2_ID_VERIFIED', '2. Identités Vérifiées (Présence)'), ('STEP3_DEED_SIGNED', '3. Acte de Vente Signé'), ('STEP4_ANDF_DEPOSITED', "4. Déposé à l'ANDF"), ('STEP5_TITLE_MODIFIED', "5. Titre Modifié par l'ANDF"), ('STEP6_COMPLETED', '6. Titre Récupéré / Terminé'), ('CANCELLED', 'Annulée')], db_index=True, default='STEP1_NOTARY_SELECTED', max_length=30)),
                ('andf_dossier_number', models.CharField(blank=True, help_text='Numéro de dépôt officiel ANDF', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step2_verified_at', models.DateTimeField(blank=True, null=True)),
                ('step3_signed_at', models.DateTimeField(blank=True, null=True)),
                ('step4_deposited_at', models.DateTimeField(blank=True, null=True)),
                ('step5_modified_at', models.DateTimeField(blank=True, null=True)),
                ('step6_completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='notaries.notary')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='land_registry.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folio de Transaction',
                'verbose_name_plural': 'Folios de Transaction',
                'db_table': 'transaction_folios',
            },
        ),
    ]
