# Generated by Django 5.2.5 on 2025-12-28 02:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('boundary', models.JSONField(help_text='Polygone GeoJSON')),
                ('chief_wallet', models.CharField(help_text='Wallet du chef de zone responsable', max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_wallet', models.CharField(help_text='Wallet du demandeur', max_length=42)),
                ('gps_at_request', models.JSONField(help_text='Localisation {lat, lng}')),
                ('min_witnesses', models.IntegerField(default=3, help_text='Nombre minimum de témoins requis')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert aux votes'), ('COMPLETED', 'Validé (Consensus atteint)'), ('REJECTED', 'Rejeté (Fraude détectée)')], db_index=True, default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WitnessVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('witness_gps', models.JSONField(help_text='Localisation {lat, lng}')),
                ('vote_result', models.BooleanField(help_text='True=Valide, False=Fraude')),
                ('signature', models.TextField(help_text='Signature cryptographique (EIP-712)')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
