# Generated by Django 5.2.5 on 2025-12-28 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consensus', '0001_initial'),
        ('land_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_requests', to='land_registry.property'),
        ),
        migrations.AddField(
            model_name='witnessvote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='consensus.validationrequest'),
        ),
        migrations.AddField(
            model_name='witnessvote',
            name='witness',
            field=models.ForeignKey(db_column='witness_wallet', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='wallet_address'),
        ),
        migrations.AlterUniqueTogether(
            name='witnessvote',
            unique_together={('request', 'witness')},
        ),
    ]
