# Generated by Django 5.2.5 on 2025-12-28 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='witnessvote',
            old_name='witness',
            new_name='witness_wallet',
        ),
        migrations.RemoveField(
            model_name='validationrequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='validationrequest',
            name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='witnessvote',
            unique_together={('request', 'witness_wallet')},
        ),
        migrations.AlterField(
            model_name='witnessvote',
            name='signature',
            field=models.CharField(help_text='Signature cryptographique (EIP-712)', max_length=255),
        ),
        migrations.AlterModelTable(
            name='geofence',
            table='geo_fences',
        ),
        migrations.AlterModelTable(
            name='validationrequest',
            table='validation_requests',
        ),
        migrations.AlterModelTable(
            name='witnessvote',
            table='witness_votes',
        ),
        migrations.RemoveField(
            model_name='witnessvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='witnessvote',
            name='created_at',
        ),
    ]
