# Generated by Django 5.2.5 on 2025-12-28 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus', '0003_rename_witness_witnessvote_witness_wallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='witnessvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='witnessvote',
            name='witness_full_name',
            field=models.CharField(default='', help_text='Nom et Prénoms complets', max_length=255),
        ),
        migrations.AddField(
            model_name='witnessvote',
            name='witness_id_number',
            field=models.CharField(default='', help_text="Numéro d'identification (NPI/CIP/CNI)", max_length=50),
        ),
        migrations.AddField(
            model_name='witnessvote',
            name='witness_phone',
            field=models.CharField(default='', help_text='Numéro de téléphone vérifié', max_length=20),
        ),
        migrations.AlterField(
            model_name='witnessvote',
            name='signature',
            field=models.CharField(help_text='Signature (Digitale ou USSD Hash)', max_length=255),
        ),
        migrations.AlterField(
            model_name='witnessvote',
            name='witness_wallet',
            field=models.ForeignKey(blank=True, db_column='witness_wallet', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='wallet_address'),
        ),
        migrations.AlterUniqueTogether(
            name='witnessvote',
            unique_together={('request', 'witness_id_number')},
        ),
    ]
