# Generated by Django 5.2.5 on 2025-12-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus', '0004_alter_witnessvote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='witnessvote',
            name='witness_birth_date',
            field=models.DateField(default='1900-01-01', help_text='Date de naissance (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='witnessvote',
            name='witness_full_name',
            field=models.CharField(help_text='Nom et Prénoms complets', max_length=255),
        ),
        migrations.AlterField(
            model_name='witnessvote',
            name='witness_id_number',
            field=models.CharField(help_text="Numéro de Passeport ou Carte d'Identité Nationale", max_length=100),
        ),
        migrations.AlterField(
            model_name='witnessvote',
            name='witness_phone',
            field=models.CharField(help_text='Numéro de téléphone de contact', max_length=20),
        ),
    ]
