# Generated by Django 5.2.5 on 2025-12-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consensus', '0005_witnessvote_witness_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witnessvote',
            name='witness_birth_date',
            field=models.DateField(blank=True, help_text='Date de naissance (YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='witnessvote',
            name='witness_phone',
            field=models.CharField(help_text='Numéro de téléphone', max_length=20),
        ),
    ]
